### PR TITLE
download operational GEFSv12 forecast and make global hazards outlook plots

### PR DESCRIPTION
**Pull request by ricampos**
There are 2 main tasks involved: (1) download of operational files from the NOAA ftp (field outputs in grib2 format) and (2) python processing that reads the grid2 files and, for a given time range (right now the default is set for week2), generates the probability maps.
The main file that manages both parts is the shell script probmaps_gefs.sh. The download is restricted to given variables (U10, Hs and Tp) using the .idx files and the auxiliar .pl codes. At the end of probmaps_gefs.sh, the python script probmaps_gefs.py is executed to process the probabilities.
The probmaps_gefs.sh requires only one input argument, which is the path where the codes and files are saved (or symbolic link), probmaps_gefs.sh, get_grib.pl, get_inv.pl, probmaps_gefs.py, probmaps_gefs.yaml; and where a directory will be created to download and save the forecast grib2 files.
The python code probmaps_gefs.py reads the configuration file probmaps_gefs.yaml, where it is IMPORTANT to edit the output path to save the resulting figures. In addition, probmaps_gefs.py also reads 4 arguments that are automatically set up in the shell script (not need to change): forecast cycle, initial/final forecast day (default 7 14, for week2), and one variable (U10, Hs, or Tp). 
The shell script loops through U10, Hs, and Tp.

The expected result includes initial percentile plots and the probability maps (main result) for the levels informed in probmaps_gefs.yaml, including U10, Hs, and Tp. The results are linked to the most recent forecast cycle (00Z).

It has been successfully tested on my local laptop and on Orion, at:
/media/ricardo/ssdwork/analysis/products/probmaps
with results at:
/work/noaa/marine/ricardo.campos/work/products/probmaps/optest
I'm keeping the outputs in this specific directory because new runs overwrite the previous cycles so, in the future, the website server can point to the same figure names. And the shell script can be added to crontab.

Other important points: remember to activate the python environment before start running the shell script (or add the load/activation to the shell script), and keep in mind it involves download so it won't run inside a submitted job (no access to the internet).
To quickly test and run, just keep all the scripts in the same directory, edit outpath inside probmaps_gefs.yaml, and execute the shell script: bash probmaps_gefs.sh /home/user/path

More detailed information can be found in the headers.

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Hi Ricardo,
I'll review this after my morning meetings.
Thanks,
Matt

**Comment by ricampos** [comment]
Thank you @JessicaMeixner-NOAA and @MatthewMasarik-NOAA .
Good point, Jessica, I think these two pearl codes are available online, I can wget them inside the shell script, which would avoid this problem. Sorry to ask, but why are you suggesting "staying away from pearl" ? I've never had any bad experiences.

**Comment by JessicaMeixner-NOAA** [comment]
Not many people know pearl to help debug it.  I know I've seen others move away from it when possible.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @ricampos, I'm reviewing this now and wanted to follow up on @JessicaMeixner-NOAA earlier comment regarding the perl scripts from another author.  You mentioned potentially using `wget` from inside the shell script as a way to replace the functionality of those scripts.  If that is the solution you plan to take, you can make that update on this branch (ricampos:probmaps), then push it to Github again, and that change will then automatically update for us to see here on the PR.  So then I can review these new updates you made, and approve the PR.  I'll wait to hear back from you to complete the review.  Also, I'm happy to help walk through the steps of updating this branch with you if that's of interest.

**Comment by ricampos** [comment]
Hi @MatthewMasarik-NOAA, I removed the two pearl scripts and added a wget to the main shell script. I tested it again and it is working fine.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
@ricampos has removed the scripts from another author.  Based on the code review and resolving this request I approve this PR.

**Pull request merged**
